language: node_js
node_js:
  - "6"
addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.2-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell
      - oracle-java8-installer
services:
  - mongodb
script: npm test
notifications:
  slack: siliconvalleybootcamp:5CgIMYv9koEBi2HTy7dWBiHv
